### PR TITLE
add virtaul interafce

### PR DESCRIPTION
**Pull request by atyg02**

### CODE REVIEW

**Comment by uminokoe** [comment]
Thanks for your contribution. Before merging, I would like to ask a few questions.

1. Does "Add virtual interface" mean something like [Wireless client and software AP with a single Wi-Fi device](https://wiki.archlinux.org/index.php/software_access_point#Wireless_client_and_software_AP_with_a_single_Wi-Fi_device)?
Using your version, my output of `iw list` is as follows:
```
...
        software interface modes (can always be added):
        interface combinations are not supported
        Device supports scan flush.
...
```
2. Out of curiosity, may I know if you have written the code by yourself, or is it derived from other versions/repositories/drivers?

For your information, I noticed that someone [reported](https://github.com/diederikdehaas/rtl8812AU/issues/63) that there is a newer version, 5.1.5. If I have time, I will also check that out to see if it brings performance improvements, new functions or bug fixes.

**Comment by Id2ndR** [comment]
Currenty it does compile on 4.10 but not in 4.11

> uminokoe-rtl8812AU/include/osdep_service.h: In function 'thread_enter':
uminokoe-rtl8812AU/include/osdep_service.h:345:2: error: implicit declaration of function 'allow_signal'; did you mean 'do_signal'? [-Werror=implicit-function-declaration]
  allow_signal(SIGTERM);
  ^~~~~~~~~~~~
  do_signal
uminokoe-rtl8812AU/include/osdep_service.h: In function 'flush_signals_thread':
uminokoe-rtl8812AU/include/osdep_service.h:355:6: error: implicit declaration of function 'signal_pending'; did you mean 'timer_pending'? [-Werror=implicit-function-declaration]
  if (signal_pending(current))
      ^~~~~~~~~~~~~~
      timer_pending
uminokoe-rtl8812AU/include/osdep_service.h:356:3: error: implicit declaration of function 'flush_signals'; did you mean 'do_signal'? [-Werror=implicit-function-declaration]
   flush_signals(current);
   ^~~~~~~~~~~~~
   do_signal
cc1: some warnings being treated as errors

**Comment by uminokoe** [comment]
@Id2ndR 
Sorry that I am still using 4.10, so it is a bit difficult for me to test. Could you please try adding the following lines to `rtl8812AU/include/osdep_service.h`:
```
#include <linux/signal.h>
#include <linux/sched/signal.h>
#include <linux/timer.h>
```

For example:
```
(...)
#ifndef __OSDEP_LINUX_SERVICE_H_
#define __OSDEP_LINUX_SERVICE_H_

#include <linux/signal.h>
#include <linux/sched/signal.h>
#include <linux/timer.h>
#include <linux/version.h>
#include <linux/spinlock.h>
(...)
```

I believe that the functions are defined in those three files, so I guess that including them may work. However I have no experience on programming or Linux kernel, so in the end I may also have to rely on others for a solution.

**Comment by Id2ndR** [comment]
Adding these 3 includes works great :). Thanks !
